name: Build and Push Frontend to GHCR

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: false
          tags: ghcr.io/stephen-hallett/scopus-check:latest
          platforms: linux/amd64

      - name: Build and push Docker image
        if: github.event_name == 'push' && success() || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: ghcr.io/stephen-hallett/scopus-check:latest
          platforms: linux/amd64

  deploy:
    needs: build
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:gh-ci

      - name: Redeploy App
        run: |
          ssh -o "StrictHostKeyChecking no" ${{ secrets.VPS_USER }}@scopus-check "
            podman pull ghcr.io/stephen-hallett/scopus-check:latest
            podman restart scopus-check
          "
